version: "3.9"
services:
  redis:
    image: redis:6.0.10
    restart: always
    env_file:
      - .redis.env        
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    env_file:
      - .elasticsearch.env
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
  minio:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    env_file:
      - .minio.env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    env_file:
      - .rabbitmq.env
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  opencti:
    image: opencti/platform:4.2.3
    env_file:
      - .platform.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:rolling
    env_file:
      - .worker.env
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 30
      placement:
        max_replicas_per_node: 10
    restart: always
   
  connector-history:
    image: opencti/connector-history:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.history.env
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.expstix.env
    restart: always
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.expcsv.env
    restart: always
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.impstix.env
    restart: always
  connector-import-file-pdf-observables:
    image: opencti/connector-import-file-pdf-observables:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.imppdf.env
    restart: always
  connector-malpedia:
    image: opencti/connector-malpedia:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.malpedia.env
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.mitre.env
    restart: always
  connector-cve:
    image: opencti/connector-cve:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.cve.env
    restart: always
  connector-cyber-threat-coalition:
    image: opencti/connector-cyber-threat-coalition:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.ctc.env
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.opencti.env
    restart: always
  connector-urlhaus:
    image: opencti/connector-urlhaus:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.urlhaus.env
    restart: always
  connector-abuseipdb:
    image: opencti/connector-abuseipdb:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.abuseipdb.env
    restart: always
  connector-hygiene:
    image: opencti/connector-hygiene:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.hygiene.env
    restart: always
  connector-ipinfo:
    image: opencti/connector-ipinfo:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.ipinfo.env
    restart: always
  connector-virustotal:
    image: opencti/connector-virustotal:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.virustotal.env
    restart: always
  connector-misp:
    image: opencti/connector-misp:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.misp.env
    restart: always
  connector-cryptolaemus:
    image: opencti/connector-cryptolaemus:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.cryptolaemus.env
    restart: always
  connector-cybercrimetracker:
    image: opencti/connector-cybercrime-tracker:4.2.3
    depends_on:
      - opencti
    env_file:
      - .con.cct.env
    restart: always
volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata: